awnumar/memguard

- internals.go
- memguard.go
* Remove type `ExitFunc` and replace with `func()`
* Replace hacky "once" code from `CatchInterrupt` with `sync.Once`.
> Simplify CatchInterrupt()

- errors.go
- memguard.go
- memguard_test.go
> Improvements

- memguard.go
Recreatable with the following script.
```
package main
import (
"fmt"
"github.com/awnumar/memguard"
)
func main() {
key, _ := memguard.New(52, false)
key.CopyAt(make([]byte, 10), 32)
fmt.Println(key.Buffer)
}
```
> CopyAt: fix panic on copy

- internals.go
- memguard.go
This PR aims to implement protection for the global canary value.
The container it is now stored in is basically a LockedBuffer but without a canary of its own, as that seemed a little cyclic.
> Protect the canary

- AUTHORS
- internals.go
- memguard.go
- memguard_test.go
As suggested in https://www.reddit.com/r/golang/comments/6s84ky/memory_security_in_go/dlcmzp3/
Some cosmetic/ux changes may be needed. `LockedBuffers()` was removed to allow implementing automatic destruction. This shouldn't be much of a problem since I can't think of any good use cases outside of `DeleteAll()`.
> Use finalizers to prevent leaks

- CONTRIBUTING.md
- docs.go
- internals.go
- memguard.go
- memguard_test.go
The recent finaliser addition involved moving the LockedBuffer's own methods into a separate struct. This messed with the documentation generated by godoc, so this PR aims to rectify that.
We add an explicit `Buffer()` method that functions identically to the old `.Buffer` syntax.
> Add Buffer() method.

- internals.go
- memcall/memcall_osx.go
- memcall/memcall_unix.go
Stop generating an ordinary slice (to initially store the canary value) to later copy from into the secure buffer. It defeats the purpose of the secure buffer.
> Fix potential leak of canary value

- internals.go
- memguard.go
- memguard_test.go
Exposing a function for wiping ordinary slices implies that it holds some kind of guarantees. In reality, wiping an ordinary slice is next to useless, since you have no idea about any copies made or what the garbage collector has done.
Instead, to only allow wiping of secure LockedBuffers, we make the WipeBytes function internal and instead expose a Wipe method for LockedBuffers.
> Replace WipeBytes with a Wipe method.

- memguard.go
To prevent regressions in the future that may cause mutex conflicts.
> internals: use internal methods

- memcall/memcall_openbsd.go
- memcall/memcall_windows.go
* Handle the platform `openbsd` explicitly.
* Use `MAP_PRIVATE` on Unix systems.
This fixes #45.
> memcall: handle openbsd explicitly

- memcall/memcall_freebsd.go
On freebsd, we have the option to tell the kernel at mmap time to disregard this memory when dumping to core files.
> freebsd: add the MAP_NOCORE flag

- container.go
- memcall/memcall_freebsd.go
- memcall/memcall_openbsd.go
- memcall/memcall_osx.go
- memcall/memcall_test.go
- memcall/memcall_unix.go
- memcall/memcall_windows.go
Like libsodium does, we now fill allocated region with 0xdb bytes in order to help catch bugs due to uninitialized data.
> alloc: use strange bytes

- internals.go
- memguard.go
- memguard_test.go
Re-add the WipeBytes function in light of the issue raised in #58. Also added a warning about its potential limitations to its documentation.
The implementation has also been improved.
Closes #58.
> feature: re-add the wipebytes function

- container.go
- internals.go
- memcall/memcall_freebsd.go
- memcall/memcall_openbsd.go
- memcall/memcall_osx.go
- memcall/memcall_test.go
- memcall/memcall_unix.go
- memcall/memcall_windows.go
- memguard_test.go
* Reverted #52; the drawbacks outweighed the pros.
* #59 has been modified given developments in the Go compiler. (Thanks to @anitgandhi for pointing them out.)
> Security and performance optimisations.

- core/buffer.go
- core/buffer_test.go
In reference to the patch in #86, the actual issue is deeper. When we set a lower limit to the length of the canary, you need more than a single page to store the reference. It's not clean. The solution in this PR is to remove the lower limit so the canary can grow from length zero (when `len(data)` equals the page size) up to one less than the page size (when `len(data)` equals 1).
When the canary has a length of zero, this is fine as the data is up against the lower guard page. Otherwise, **with some values**, the canary will be small but this is a reasonable trade-off.
> canary: remove lower bound limit on length

- buffer.go
- buffer_test.go
- core/buffer_test.go
- core/enclave_test.go
- examples/README.md
- examples/socketkey/socketkey.go
- examples/stdin/stdin.go
This change also makes reading from stdin very easy:
```go
b := NewBufferFromReaderUntil(os.Stdin, '\n')
```
> Add LockedBuffer constructors that use Reader objects as sources

- buffer.go
- buffer_test.go
The rationale for this is that I've seen people use this library and just call `string(b.Bytes())` whenever they need a string representation, which creates a copy of the data and should be avoided. The added method returns a string referencing the same portion of memory. This way we can mutate the string by mutating the underlying memory, and there are no copies made.
> Add String method

- core/coffer.go
- core/coffer_test.go
- core/enclave.go
- core/exit.go
- core/exit_test.go
- Remove interval specification functionality.
- Increase interval to half a second.
- Make the static allocation for fast random bytes reading local to the coffer object.
- Add check to prevent Coffer being created twice.
> Some localisation

- AUTHORS
- core/buffer.go
- core/exit.go
- core/exit_test.go
> Redesigning safe termination functionality

- buffer.go
- core/buffer.go
- core/coffer.go
- core/crypto.go
- core/enclave.go
- core/exit.go
- memguard.go
fix two types of Mutex bug
1. RLock following RLock
2. Lock following RLock
*core.Panic() is a big challenge, it requires coffer and all lockbuffers write permission if any error occurs.*
> Fix recursive lock

- .cirrus.yml
Github Action for windows was failing because gcc was not installed on windows runner. This fixes this issue by installing mingw onto the windows runner, which will install gcc
Error that this fixes
```
C:\golang\src\github.com\awnumar\memguard>call env CGO_ENABLED=1 go test -race -v ./... 
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in %PATH%
FAIL	github.com/awnumar/memguard [build failed]
FAIL	github.com/awnumar/memguard/core [build failed]
FAIL	github.com/awnumar/memguard/examples/casting [build failed]
FAIL	github.com/awnumar/memguard/examples/deadlock/x01 [build failed]
FAIL	github.com/awnumar/memguard/examples/socketkey [build failed]
?   	github.com/awnumar/memguard/examples/stdin	[no test files]
?   	github.com/awnumar/memguard/examples/streams	[no test …
```
> Fixes windows and FreeBSD ci failures

- buffer.go
- buffer_test.go
This PR addresses an issue in memguard where the go garbage collector (GC) will trigger the finalizer on a LockedBuffer, zeroing out and freeing this buffer while the running code may still have a pointer to this buffer. This can result in the code being run against partially or fully zero'd out memory.
This issue was originally privately disclosed to memguard and it was agreed that due to the minor security impact, a public PR should be opened to track one possible solution to this problem.
The Fix
====
We fix this issue by removing the finalizer from the LockedBuffer. To wipe the LockedBuffer and free the associated memory the developer must call `Destroy()`. This is a reasonable fix because memguard provides additional security at the cost of requiring the developer managing this …
> Removes drop based finalizer
